services:
  mongo:
    image: 'mongo:latest'
    container_name: mongo
    restart: always
    environment:
      - 'MONGO_INITDB_DATABASE=sicoesdb'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017:27017'
  tomcat:
    image: douglascamposh/scrapsicoes
    container_name: scrapsicoes
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      - mongo
    restart: always
    ports:
      - 8050:8050
  next:
    image: douglascamposh/sicoesweb
    container_name: sicoesweb
    depends_on:
      - tomcat
    ports:
      - 3000:3000

